package com.cryptotrader.data.remote.claude.dto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Claude API request/response DTOs
 */

@JsonClass(generateAdapter = true)
data class ClaudeRequest(
    @Json(name = "model") val model: String = "claude-sonnet-4-5-20250929",
    @Json(name = "max_tokens") val maxTokens: Int = 4096,
    @Json(name = "messages") val messages: List<ClaudeMessage>,
    @Json(name = "temperature") val temperature: Double = 0.7,
    @Json(name = "system") val system: String? = null
)

@JsonClass(generateAdapter = true)
data class ClaudeMessage(
    @Json(name = "role") val role: String, // "user" or "assistant"
    @Json(name = "content") val content: String
)

@JsonClass(generateAdapter = true)
data class ClaudeResponse(
    @Json(name = "id") val id: String = "",
    @Json(name = "type") val type: String = "",
    @Json(name = "role") val role: String = "",
    @Json(name = "content") val content: List<ClaudeContent> = emptyList(),
    @Json(name = "model") val model: String = "",
    @Json(name = "stop_reason") val stopReason: String? = null,
    @Json(name = "usage") val usage: ClaudeUsage? = null
)

@JsonClass(generateAdapter = true)
data class ClaudeContent(
    @Json(name = "type") val type: String = "",
    @Json(name = "text") val text: String = ""
)

@JsonClass(generateAdapter = true)
data class ClaudeUsage(
    @Json(name = "input_tokens") val inputTokens: Int = 0,
    @Json(name = "output_tokens") val outputTokens: Int = 0
)

/**
 * Trading strategy configuration generated by Claude
 */
@JsonClass(generateAdapter = true)
data class StrategyConfig(
    @Json(name = "id") val id: String,
    @Json(name = "name") val name: String,
    @Json(name = "description") val description: String,
    @Json(name = "indicators") val indicators: List<Indicator>,
    @Json(name = "entry_conditions") val entryConditions: List<String>,
    @Json(name = "exit_conditions") val exitConditions: List<String>,
    @Json(name = "position_sizing") val positionSizing: PositionSizing,
    @Json(name = "risk_management") val riskManagement: RiskManagement,
    @Json(name = "trading_pairs") val tradingPairs: List<String>,
    @Json(name = "risk_level") val riskLevel: String = "MEDIUM",
    @Json(name = "confidence_score") val confidenceScore: Double = 0.0
)

@JsonClass(generateAdapter = true)
data class Indicator(
    @Json(name = "name") val name: String,
    @Json(name = "type") val type: String,
    @Json(name = "period") val period: Int? = null,
    @Json(name = "source") val source: String = "close"
)

@JsonClass(generateAdapter = true)
data class PositionSizing(
    @Json(name = "type") val type: String, // "fixed_percentage", "kelly_criterion", "volatility_based"
    @Json(name = "value") val value: Double
)

@JsonClass(generateAdapter = true)
data class RiskManagement(
    @Json(name = "stop_loss_percent") val stopLossPercent: Double,
    @Json(name = "take_profit_percent") val takeProfitPercent: Double,
    @Json(name = "max_open_positions") val maxOpenPositions: Int
)
